name: 'Build .NET Core app'
inputs:
  work-dir:
    description: "Path to the solution/project file"
    required: false
    type: string
    default: "."
  dotnet-version:
    description: "Version of .NET Core SDK to use"
    required: false
    type: string
    default: "8.x"
  run-tests:
    description: "Run tests"
    required: false
    type: boolean
    default: false
  signing-key:
    description: "Signing key for the assembly"
    required: false
    type: string
outputs:
  release-notes:
    description: "Generated release notes"
    value: ${{ steps.release-notes.outputs.result }}

branding:
  icon: 'check'
  color: 'green'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check for .NET Version Env Var
      id: check_dotnet
      shell: bash
      run: |
        if [ -z "${{ env.DOTNET_VERSION }}" ]; then
          echo "DOTNET_VERSION not set."
          echo "setup_required=true" >> $GITHUB_ENV
        else
          echo "DOTNET_VERSION is set to $DOTNET_VERSION."
          echo "setup_required=false" >> $GITHUB_ENV
        fi

    - name: Setup .NET ${{ inputs.dotnet-version }}
      if: env.setup_required == 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '${{ inputs.dotnet-version }}'

    - name: Set DOTNET_VERSION if not set
      if: env.setup_required == 'true'
      shell: bash
      run: echo "DOTNET_VERSION=${{ inputs.dotnet-version }}" >> $GITHUB_ENV

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.work-dir }}
      run: dotnet restore


    - name: Build (with signing)
      if: ${{ inputs.signing-key != '' }}
      shell: bash
      working-directory: ${{ inputs.work-dir }}
      run: |
        dotnet build --configuration Release --no-restore /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=${{ inputs.signing-key }}

    - name: Build (without signing)
      if: ${{ inputs.signing-key == '' || inputs.signing-key == null }}
      shell: bash
      working-directory: ${{ inputs.work-dir }}
      run: dotnet build --configuration Release --no-restore

    - name: Test
      if: ${{ inputs.run-tests == 'true' }}
      shell: bash
      working-directory: ${{ inputs.work-dir }}
      run: dotnet test --no-restore --verbosity normal

    - name: Publish Nuget Required
      id: publish-nuget
      shell: bash
      run: |
        if [ -z "$NUGET_API_KEY" ]; then
          echo "configured=false" >> $GITHUB_OUTPUT
          echo "NuGet API key is empty or not set!"
        else
          echo "configured=true" >> $GITHUB_OUTPUT
          echo "NuGet API key length: ${#NUGET_API_KEY}"
          echo "First 4 chars: ${NUGET_API_KEY:0:4}"
        fi

    - name: Get Release Notes
      uses: actions/github-script@v6
      if: ${{ steps.publish-nuget.outputs.configured == 'true' }}
      id: release-notes
      env:
        tag_name: ${{ github.event.release.tag_name }}
        repo_name: ${{ github.event.repository.name }}
        repo_owner: ${{ github.repository_owner }}
      with:
        retries: 3
        script: |
          console.log("Owner:"+process.env.repo_owner);
          console.log("Repo:"+process.env.repo_name);
          var result = await github.rest.repos.getReleaseByTag({
            tag: process.env.tag_name,
            owner: process.env.repo_owner,
            repo: process.env.repo_name
          });
          return result.data.body;

    - name: Create release notes file
      if: ${{ steps.publish-nuget.outputs.configured == 'true' }}
      shell: bash
      working-directory: ${{ inputs.work-dir }}
      run: |
        printf "%s" ${{ steps.release-notes.outputs.result }} > release-notes.txt

    - name: Pack with Signing
      if: ${{ inputs.signing-key != '' && steps.publish-nuget.outputs.configured == 'true' }}
      shell: bash
      working-directory: ${{ inputs.work-dir }}
      run: |
        dotnet pack -c Release --no-build /p:Version=${{ github.event.release.tag_name }} /p:ReleaseNotesFile=release-notes.txt /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:ContinuousIntegrationBuild=true /p:EmbedUntrackedSources=true /p:PublishRepositoryUrl=true /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=${{ inputs.signing-key }}

    - name: Pack without Signing
      if: ${{ (inputs.signing-key == '' || inputs.signing-key == null) && steps.publish-nuget.outputs.configured == 'true' }}
      shell: bash
      working-directory: ${{ inputs.work-dir }}
      run: |
        dotnet pack -c Release --no-build /p:Version=${{ github.event.release.tag_name }} /p:ReleaseNotesFile=release-notes.txt /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:ContinuousIntegrationBuild=true /p:EmbedUntrackedSources=true /p:PublishRepositoryUrl=true

    - name: Publish Nuget Package
      if: ${{ steps.publish-nuget.outputs.configured == 'true' }}
      shell: bash
      working-directory: ${{ inputs.work-dir }}
      run: dotnet nuget push **/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
